tasks:
  - init: |
      docker compose pull
  - command: |
      docker compose up

ports:
  - name: Prometheus
    port: 9090
    onOpen: open-browser
    visibility: private
  - name: Grafana
    port: 3000
    onOpen: open-browser
    visibility: private
  - name: App
    port: 8080
    onOpen: open-browser
    visibility: public